### ISSUE TITLE
Usability checklist

### ISSUE THREAD

**Issue by usetech-llc** [usetech-llc/apps#36]
- [ ] Check usability of the maximum bondable amount

- [ ] Help items for flow

- [ ] Warning abound 7 days bonding - delete number of blocks part

- [ ] Cut out QR Code

- [ ] "Initializing waller" reword

- [ ]  add Kusama sign to the place where later we can add the network change

- [ ] For users who have more then one account consider making a list and having ONE set of actionable buttons

- [ ] intro wizard and tips

- [ ] navigation for different target audiences (Using a traditional NavBar would probably help any user to understand the UI better (https://getbootstrap.com/docs/4.5/components/navbar/)

- [ ] icon/text for the Rewards button (and others)

- [ ] redesign dropdown for simpler understanding

- [ ] Official components only partly ‘disconnected’.
I cannot make a screenshot here but hovering an account shows a “?” that does nothing…  Cut it out
